/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
 

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function AnimatedPlane(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/AnimatedPlane.gltf')
  const { actions,names } = useAnimations(animations, group)

  useEffect(()=>{
    console.log(actions)
    console.log(names)
    actions[names[0]].reset().fadeIn(0.5).play()
  },[])
  return (
    <group ref={group} {...props} dispose={null}   scale={0.25}  position={[-0.9,0.1,-8.3]} >
      <group    >
        <mesh
          name="AnimatedPlane"
          castShadow
          receiveShadow
          geometry={nodes.AnimatedPlane.geometry}
          
          rotation={[0, 0, 0]}
        
        ><meshStandardMaterial color={"white"}/></mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/AnimatedPlane.gltf')

 
