/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { DoubleSide } from 'three'

export default function Map(props) {
  const { nodes, materials } = useGLTF('/models/Map.gltf')
  return (
    <group {...props} dispose={null} scale={0.2} >
      <mesh castShadow receiveShadow geometry={nodes.Map.geometry} ><meshBasicMaterial side={DoubleSide}/></mesh>
    </group>
  )
}

// rotation={[0.0,Math.PI,0.0]}

useGLTF.preload('/models/Map.gltf')
