/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {
  MeshPortalMaterial,
  OrbitControls,
  OrthographicCamera,
  PerspectiveCamera,
} from "@react-three/drei";
import { DoubleSide } from 'three';
export default function Platforms(props) {
  const { nodes, materials } = useGLTF('/models/Platforms.gltf')
  
  return <>
   
    <group {...props} dispose={null}>
      <mesh scale={0.008}
        castShadow
        receiveShadow
        geometry={nodes.Platforms.geometry}

      >
        <meshStandardMaterial color={"#f9f9f9"} side={DoubleSide}/>
      </mesh>
    </group>
  </>
}

useGLTF.preload('/models/Platforms.gltf')
